import type { Metadata } from "next";
import { Inter, Roboto } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Image from "next/image";

// const inter = Inter({ subsets: ["latin"] });
const roboto = Roboto({ weight: "900", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <header className="flex items-center justify-center p-2">
          <div className="flex items-center">
            <Link href="/">
              <Image
                src="/SUPERDANKO_piksa.png"
                alt="logo"
                width={70}
                height={70}
              />
            </Link>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
